[package]
name = "raytrace"
version = "0.1.0"
authors = ["luxrck"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
nalgebra = "0.19"
rayon = "1.3"
image = "0.22"
